spring-cloud/spring-cloud-dataflow-ui

ui/app/scripts/analytics/controllers/counters.js, ui/app/scripts/analytics/controllers/dashboard.js, ui/app/scripts/analytics/views/analytics.html
This resolves spring-cloud/spring-cloud-dataflow-ui#17
* Uncomment analytics tabs that are un-implemented
* Remove REST calls for un-implemented metrics
=> GH-17 Fix analytics tab

ui/app/scripts/shared/services.js, ui/app/scripts/shared/views/about.html
Resolves https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/2
Depends on: https://github.com/spring-cloud/spring-cloud-dataflow/issues/299
=> gh-2 Add SPI type and version in 'about' section

ui/app/scripts/analytics/controllers/dashboard.js, ui/app/scripts/analytics/controllers/metric.js
=> gh-27 Enable FieldValueCounter widgets

ui/Gruntfile.js, ui/app/scripts/directives.js, ui/app/scripts/job/controllers/executions.js, ui/app/scripts/job/services.js, ui/app/scripts/job/views/execution-details.html, ui/app/scripts/job/views/executions.html
Also addresses:
* gh-34 Implement Job Deployment
* gh-35 Implement Job Execution details page
- Ensure task execution id is featured on job execution list page
- Ensure task execution id is featured on job execution details page
Resolves spring-cloud/spring-cloud-dataflow-ui#33
Resolves spring-cloud/spring-cloud-dataflow-ui#34
Resolves spring-cloud/spring-cloud-dataflow-ui#35
For reference, please keep in mind: spring-cloud/spring-cloud-dataflow#496
=> gh-33 Implement Job Executions List

ui/app/scripts/job/views/stepexecution-details.html
Resolves spring-cloud/spring-cloud-dataflow-ui/#41
=> gh-41 Fix Step Execution Context not rendered

ui/app/scripts/container/controllers/containers.js, ui/app/scripts/container/views/containerlist.html
Resolves spring-cloud-dataflow-ui/issues#39
=> gh-39 Fix listing of runtime modules

ui/app/styles/analytics.less, ui/app/styles/flo.less, ui/app/styles/header.less, ui/app/styles/main.less
Resolves spring-cloud/spring-cloud-dataflow-ui#6
=> PUI colours. Remove duplicate css classes.

ui/Gruntfile.js, ui/app/404.html, ui/app/scripts/auth/controllers/logout.js, ui/app/scripts/shared/interceptors.js
Is depended on by https://github.com/spring-cloud/spring-cloud-dataflow/issues/646
Resolves spring-cloud/spring-cloud-dataflow-ui#32
=> gh-32 UI - Change `Admin` -> `Dashboard`

ui/app/scripts/job/controllers/executions.js, ui/app/scripts/task/controllers/executions.js
=> Add null check on task/job executions result

ui/app/scripts/app/views/apps-list.html, ui/app/scripts/task/views/apps.html
Resolves spring-cloud/spring-cloud-dataflow-ui#87
=> gh-87 Add hint to indicate the requirement to register applications

ui/bower.json
Resolves spring-cloud/spring-cloud-dataflow-ui#116
=> Modify spring-flo dependency to v0.5.1 release

ui/app/scripts/app/controllers/bulk-import-apps.js
Resolves https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/119
=> Update app starters bulk upload URLs

ui/bower.json
Now spring-flo 0.6.0 is done, move to that version in the UI.
=> Change from flo master version to 0.6.0

ui/app/index.html, ui/app/scripts/app/views/apps-list.html, ui/app/scripts/auth/controllers/login.js, ui/app/scripts/auth/services.js, ui/app/scripts/directives.js, ui/app/scripts/routes.js, ui/app/scripts/shared/views/roles-missing.html, ui/app/scripts/stream/views/definitions.html, ui/app/scripts/stream/views/streams.html, ui/app/scripts/task/views/definitions.html
resolves https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/155
=> gh-155 Make the Dashboard Role-aware

ui/app/scripts/shared/views/about.html
Resolves https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/159
=> gh-159 Update links in the "About" tab

ui/app/scripts/app/controllers/bulk-import-apps.js, ui/app/scripts/app/views/bulk-import-apps.html
Resolves https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/165
=> gh-165 Remove bulk-registration of apps from the UI

ui/app/scripts/task/controllers/definitions.js, ui/app/scripts/task/controllers/detailed-task.js
=> Adapt to use composed flag on TaskDefinitionResource

ui/app/scripts/stream/views/app-deployed-tooltip.html
resolves https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/200
=> gh-200 Remove port, host, ip and group from Metrics tooltip

ui/app/scripts/stream/controllers/stream.js, ui/app/scripts/stream/views/app-deployed-tooltip.html, ui/app/styles/flo.less
=> Truncate text with ellipsis tooltip width adjusted based on content

ui/src/app/streams/stream-definitions/stream-definitions.component.ts, ui/src/app/streams/stream-deploy/stream-deploy-validators.ts, ui/src/app/streams/stream-deploy/stream-deploy.component.ts, ui/src/app/streams/streams.service.ts
=> Added JSDocs to Stream Definition Module

ui/src/app/about/about-details.component.ts, ui/src/app/about/about.component.ts, ui/src/app/app.component.ts, ui/src/app/apps/app-details/app-details.component.ts, ui/src/app/apps/apps-bulk-import.component.ts, ui/src/app/apps/apps-register/apps-register.component.ts, ui/src/app/apps/apps.component.ts, ui/src/app/apps/apps.module.ts, ui/src/app/apps/apps.service.spec.ts, ui/src/app/apps/apps.service.ts, ui/src/app/apps/model/detailed-app-registration.ts, ui/src/app/runtime/runtime-routing.module.ts, ui/src/app/shared/model/pageInfo.ts, ui/src/app/shared/services/shared-apps.service.ts, ui/src/app/shared/shared.module.ts, ui/src/app/streams/stream-definitions/stream-definitions.component.ts, ui/src/app/streams/stream-deploy/stream-deploy.component.ts, ui/src/app/streams/stream-details/stream-details.component.ts, ui/src/app/streams/streams.service.ts, ui/src/app/tasks/task-app-details/task-app-details.component.ts, ui/src/app/tasks/task-apps/task-apps.component.ts, ui/src/app/tasks/task-bulk-define/task-bulk-define.component.ts, ui/src/app/tasks/task-definitions/task-definitions.component.ts, ui/src/app/tasks/tasks.module.ts
=> Removes unnecessary imports from angular classes

ui/src/app/shared/components/property-table/property-table.component.ts, ui/src/app/shared/components/tabs.component.ts, ui/src/app/shared/components/tri-state-button.component.ts, ui/src/app/shared/components/tri-state-checkbox.component.ts, ui/src/app/shared/directives/click-outside.directive.ts
resolves #301
Also fixed one lint error
=> Added JSDocs to some of the shared components

ui/src/app/analytics/analytics.component.html, ui/src/app/jobs/jobs.component.html, ui/src/app/streams/stream-create/stream-create.component.html, ui/src/app/tasks/task-create-composed-task/task-create-composed-task.component.html
=> Provided a  message for pages under development

ui/src/app/runtime/model/runtime-app.ts, ui/src/app/runtime/runtime-apps.component.html, ui/src/app/runtime/runtime-apps.service.ts, ui/src/app/shared/pipes/key-value-filter.pipe.ts
=> Fix runtime attributes

pom.xml, ui/package.json
resolves https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/330
=> gh-330 Fix Windows Maven Build

ui/src/app/streams/stream-definitions/stream-definitions.component.html, ui/src/app/streams/stream-details/stream-details.component.html
resolves https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/328
=> gh-328 Add boilerplate text instead of TBD for tabs/view under development

ui/src/app/about/about-details.component.html, ui/src/app/app.component.html, ui/src/app/app.component.ts, ui/src/app/apps/apps-bulk-import.component.html, ui/src/app/apps/apps-register/apps-register.component.html, ui/src/app/apps/apps.component.html, ui/src/app/shared/components/tri-state-button.component.ts, ui/src/app/shared/directives/click-outside.directive.ts, ui/src/app/shared/shared.module.ts, ui/src/app/streams/stream-definitions/stream-definitions.component.html, ui/src/app/tasks/task-definitions/task-definitions.component.html, ui/src/styles.scss
resolves https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/321
=> gh-321 CSS Polishing and Cleanup

ui/src/app/tasks/task-create/task-create.component.spec.ts
Merged the previous PR without siting this test.  So I added it ;-)
resolves #343
=> Added test for back button.

ui/src/styles.scss
=> Fix pivotal-ui-git-clone components path

ui/src/app/apps/apps.service.ts
* Add needed import `rxjs/add/observable/forkJoin`
resolves https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/339
=> gh-339 App registration button is unresponsive

ui/src/app/jobs/job-execution-details/job-execution-details.component.html, ui/src/app/jobs/job-execution-details/job-execution-details.component.spec.ts, ui/src/app/jobs/step-execution-details/step-execution-details.component.html, ui/src/app/jobs/step-execution-details/step-execution-details.component.spec.ts, ui/src/app/tests/mocks/jobs.ts
* Also fixes the templates so tables and headers that should not appear on empty pages will not show.
* Also Adds "No Step Execution" message for the Step Execution Page.
resolves #360
=> Adds tests for invalid Step and Job Execution ID for detail page.

ui/src/app/streams/stream-create/stream-create.component.ts
metamodel needs to be package level.
Fix lint issues
resolves #366
=> Fixes build break

ui/src/app/streams/stream-definitions/stream-definitions.component.html
- Remove labels and just use icons.
- Polish table styles as things look
a bit weird when window is narrow.
- Fixes #384
=> Switch action buttons to icons

ui/src/app/streams/flo/flo.scss, ui/src/app/streams/flo/properties/properties-dialog.component.scss
Fixes #428 from Flo side
@ghillert here the Flo side PR for the issue
=> Adopt changes in PUI css vars and mixins location

ui/package.json, ui/src/styles.scss
resolves https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/428
=> gh-428 Fix Pivotal UI path issues

README.md, ui/README.md
* Removing old commands
* Requires readme in the UI directory for doc generation and one in the main dir for github.
resolves #436
=> Updating README with latest build instructions

ui/src/app/analytics/analytics.service.ts
=> Removes dashboard item poller when dashboard item is removed.

ui/src/app/streams/flo/text-to-graph.spec.ts, ui/src/app/streams/flo/text-to-graph.ts
=> Ensure only first link in a stream def can be marked tap link

ui/package.json, ui/src/app/shared/flo/support/app-metadata.ts, ui/src/app/shared/flo/support/properties-group-model.ts
=> Fix default boolean properties for the dialog

ui/src/app/about/about-details.component.html, ui/src/app/about/about-details.component.spec.ts, ui/src/app/about/about-info.model.ts, ui/src/app/about/about.component.html, ui/src/app/about/about.service.spec.ts, ui/src/app/tests/mocks/about.ts
=> UI now supports checksum for data flow components

ui/package.json
resolves https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/562
=> gh-562 Update Moment.js to `2.19.3`

.gitignore, ui/src/app/about/about-details.component.html
=> About-details labels to reflect the server mode

ui/src/app/shared/flo/support/app-metadata.ts, ui/src/app/streams/model/stream-definition.spec.ts, ui/src/app/streams/model/stream-definition.ts, ui/src/app/streams/stream-definitions/deployment-properties-info/deployment-properties-info.component.html, ui/src/app/streams/stream-definitions/deployment-properties-info/deployment-properties-info.component.scss, ui/src/app/streams/stream-definitions/deployment-properties-info/deployment-properties-info.component.spec.ts, ui/src/app/streams/stream-definitions/deployment-properties-info/deployment-properties-info.component.ts, ui/src/app/streams/stream-definitions/stream-definitions.component.html, ui/src/app/streams/stream-definitions/stream-definitions.component.scss, ui/src/app/streams/stream-definitions/stream-definitions.component.spec.ts, ui/src/app/streams/stream-definitions/stream-definitions.component.ts, ui/src/app/streams/stream-graph-definition/stream-graph-definition.component.html, ui/src/app/streams/stream-graph-definition/stream-graph-definition.component.scss, ui/src/app/streams/stream-graph-definition/stream-graph-definition.component.ts, ui/src/app/streams/streams.module.ts, ui/src/app/streams/streams.service.spec.ts, ui/src/app/streams/streams.service.ts
Fixes #572 
Fixes #587 
Pop-over instead of the dialog.
Column remains to be `status` column
The pop-over content has minimum styling for now.
No tests added, but if it looks good I'll add some tests as well.
=> Stream deployment info popup

ui/src/app/app.component.ts, ui/src/app/apps/apps.component.html, ui/src/app/streams/stream-definitions/stream-definitions.component.html, ui/src/app/tasks/task-definitions/task-definitions.component.html, ui/src/styles.scss
=> gh-582 Polish CSS styles

ui/src/app/streams/model/plateform.spec.ts, ui/src/app/streams/model/platform.ts, ui/src/app/streams/stream-definitions/deployment-properties/deployment-properties.component.html, ui/src/app/streams/stream-definitions/deployment-properties/deployment-properties.component.spec.ts, ui/src/app/streams/stream-definitions/deployment-properties/deployment-properties.component.ts, ui/src/app/streams/stream-definitions/stream-definitions.component.html, ui/src/app/streams/stream-definitions/stream-definitions.component.spec.ts, ui/src/app/streams/stream-definitions/stream-definitions.component.ts, ui/src/app/streams/stream-deploy-multi/stream-deploy-multi.component.html, ui/src/app/streams/stream-deploy-multi/stream-deploy-multi.component.spec.ts, ui/src/app/streams/stream-deploy-multi/stream-deploy-multi.component.ts, ui/src/app/streams/stream-deploy/stream-deploy.component.html, ui/src/app/streams/stream-deploy/stream-deploy.component.spec.ts, ui/src/app/streams/stream-deploy/stream-deploy.component.ts, ui/src/app/streams/streams.module.ts, ui/src/app/streams/streams.service.ts, ui/src/app/tests/mocks/modal.ts, ui/src/app/tests/mocks/shared-about.ts, ui/src/app/tests/mocks/streams.ts
=> gh-600 Add platform-list to stream deployment page

ui/src/app/streams/stream-create-dialog/stream-create-dialog.component.html
=> Create Stream: Pressing "return" submit form

ui/src/app/apps/app-details/app-details.component.ts, ui/src/app/apps/app-versions/app-versions.component.ts
Related https://github.com/spring-cloud/spring-cloud-dataflow-ui/commit/e5ee8845777dee62d7a15a646952764b4b198288
Fix type ApplicationType parameter
=> Fix bug versions (error parameter type)

ui/src/app/apps/app-versions/app-versions.component.html, ui/src/app/apps/apps/apps.component.html
resolves https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/631
=> gh-631 Change the description in manage-versions page

ui/package.json, ui/src/app/shared/flo/properties/properties-dialog.component.html, ui/src/app/shared/flo/properties/properties-dialog.component.ts, ui/src/app/shared/flo/support/app-ui-property.ts, ui/src/app/shared/flo/support/graph-node-properties-source.ts, ui/src/app/shared/flo/support/properties-group-model.ts, ui/src/app/streams/flo/editor.service.ts, ui/src/app/streams/flo/properties/stream-properties-dialog.component.ts, ui/src/app/streams/flo/properties/stream-properties-source.ts, ui/src/app/tasks/flo/editor.service.ts, ui/src/app/tasks/flo/node/node.component.html, ui/src/app/tasks/flo/properties/task-properties-dialog-component.ts, ui/src/app/tasks/flo/properties/task-properties-source.ts
Fixes #649 
Work on making it easier to re-use Flo properties dialog for non-graph input.
(There were no tests for this code before, no tests added now, but should be easier to test this code now. Tests to be added in the future)
=> Generalized properties dialog

ui/src/app/apps/apps-unregister/apps-unregister.component.ts
- Add error event subscription and display error message from the error handler
Resolves #658
=> Error handling during app unregistration

ui/src/app/streams/stream-deploy/stream-deploy.component.html
=> Stream Deployment: wording

ui/src/app/streams/stream-create-dialog/stream-create-dialog.component.scss
=> Style check-box and label on create stream dialog

ui/package.json
=> Update to latest Flo with performance fixes

ui/src/app/streams/streams-routing.module.ts, ui/src/app/streams/streams/streams.component.ts
=> Fix Streams Routing

ui/package.json
=> Upgrade Flo to 0.7.3

ui/src/app/tasks/tasks.service.ts
=> Fix launching task

ui/package.json
=> Flo from master to take fix for graph clear function

ui/src/app/shared/flo/properties/properties-dialog.component.html
=> Return key submits app-properties dialog form

ui/src/app/apps/apps/apps.component.html, ui/src/app/apps/apps/apps.component.spec.ts, ui/src/app/runtime/runtime-app/runtime-app.component.html, ui/src/app/runtime/runtime-app/runtime-app.component.spec.ts, ui/src/app/shared/components/loader/loader.component.ts, ui/src/app/shared/components/truncator/trail-position-type.model.ts, ui/src/app/shared/components/truncator/truncator-width-provider.directive.ts, ui/src/app/shared/components/truncator/truncator.component.spec.ts, ui/src/app/shared/components/truncator/truncator.component.ts, ui/src/app/shared/shared.module.ts, ui/src/scss/styles.scss
- Add TruncatorWidthProviderDirective
- Add TruncatorComponent
- Add basic tests
resolves https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/705
resolves https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/687
=> gh-705 Add truncator component

ui/package.json
@sabbyanandan @ghillert @oodamien Upgrade Flo to 0.7.4 release
=> Upgrade Flo to 0.7.4

ui/package.json, ui/src/app/streams/components/flo/text-to-graph.ts, ui/src/app/streams/stream-create/stream-create.component.ts
Safer fix in Flo. Adopted in SCDF UI. text->graph converter change is the culprit for the observed behaviour.
Resolves spring-cloud/spring-cloud-dataflow-ui#766
=> Adopt Flo 0.7.5 fixes

ui/src/app/apps/apps-register/apps-register.component.spec.ts, ui/src/app/apps/apps-register/apps-register.validator.spec.ts, ui/src/app/apps/apps-register/apps-register.validator.ts
=> Register Applications: update validation rule name

ui/src/app/streams/stream-deploy/builder/builder.component.ts, ui/src/app/streams/stream-deploy/stream-deploy.component.ts, ui/src/app/streams/stream-deploy/stream-deploy.service.ts, ui/src/app/streams/stream/summary/stream-summary.component.html, ui/src/app/streams/streams/streams.component.html
Resolves #625 
Issue:
Platform property is not saved on stream deploy.
=> Stream Deploy Edit

ui/src/app/streams/components/flo/editor.service.spec.ts, ui/src/app/streams/components/flo/editor.service.ts
Fixes #790 
Decided to not validate properties for now.
A better solution will be described in an issue to be created soon...
=> Disable properties validation in Flo graph for streams

ui/src/app/streams/streams-destroy/streams-destroy.component.spec.ts, ui/src/app/streams/streams-destroy/streams-destroy.component.ts
- Update tests
resolves https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/807
=> gh-807 Fix messaging when deleting a stream

ui/src/app/apps/apps-bulk-import/apps-bulk-import.component.html
resolves https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/803
=> gh-803 Fix bogus text in bulk registration page

ui/src/app/apps/apps-register/apps-register.validator.spec.ts, ui/src/app/apps/apps-register/apps-register.validator.ts
Added docker artifact regex validation
Added tests for docker artifact
Resolves #814
=> App registration: fix URI validation for a docker artifact

ui/src/app/auth/support/security-aware-request-options.ts
resolves https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/832
=> gh-832 Fix Triggering App Default fails with an infinite redirect

ui/package.json, ui/src/app/shared/flo/flo.scss, ui/src/app/streams/components/flo/editor.service.spec.ts, ui/src/app/streams/components/flo/editor.service.ts, ui/src/app/streams/components/flo/render.service.ts, ui/src/app/streams/components/flo/support/layout.ts, ui/src/app/streams/components/flo/support/shapes.ts, ui/src/app/streams/components/flo/support/view-helper.ts, ui/src/app/streams/components/stream-graph-definition/stream-graph-definition.component.ts, ui/src/app/tasks/components/flo/editor.service.ts, ui/src/app/tasks/components/flo/render.service.ts, ui/src/app/tasks/components/flo/support/shapes.ts
Fixes https://github.com/spring-projects/spring-flo/issues/30
Needs to be adopted on SCDF UI side
@sabbyanandan there is no issue on the SCDF UI side for this.
=> Adopt JointJS 2.x for Flo

ui/src/app/shared/shared.module.ts
=> ToastrMessage: Update config to enable HTML

ui/src/scss/pui.scss
=> Update PUI import SCSS

ui/src/app/tasks/task-schedule-create/task-schedule-create.component.ts
=> Schedule creation: fix error message on creation

ui/src/app/streams/stream/stream.component.html, ui/src/app/streams/stream/stream.component.ts
=> Stream page: fix stream name

ui/src/app/streams/components/stream-history-status/stream-status.component.spec.ts, ui/src/app/streams/components/stream-history-status/stream-status.component.ts, ui/src/app/streams/components/stream-status/stream-status.component.ts, ui/src/app/streams/model/stream-history.spec.ts, ui/src/app/streams/model/stream-history.ts, ui/src/app/streams/stream/history/stream-history.component.html, ui/src/app/streams/stream/history/stream-history.component.spec.ts, ui/src/app/streams/stream/history/stream-history.component.ts, ui/src/app/streams/stream/stream.component.html, ui/src/app/streams/stream/stream.component.spec.ts, ui/src/app/streams/stream/stream.component.ts, ui/src/app/streams/stream/styles.scss, ui/src/app/streams/streams-routing.module.ts, ui/src/app/streams/streams.module.ts, ui/src/app/streams/streams.service.ts, ui/src/app/tests/mocks/streams.ts
If skipper is enabled, display the history tab on the stream page.
Resolves #841
=> Stream History

ui/src/app/apps/app-details/app-details.component.html, ui/src/app/apps/app-details/app-details.component.ts, ui/src/app/shared/flo/properties/properties-dialog.component.html, ui/src/app/shared/flo/properties/properties-dialog.component.ts
Resolves #879 
Wait for merge #774
=> App Details: add all properties

ui/proxy.conf.json, ui/src/app/app.module.ts, ui/src/app/audit/audit-record-details/audit-record-details.component.html, ui/src/app/audit/audit-record-details/audit-record-details.component.spec.ts, ui/src/app/audit/audit-record-details/audit-record-details.component.ts, ui/src/app/audit/audit-record-details/styles.scss, ui/src/app/audit/audit-record-routing.module.ts, ui/src/app/audit/audit-record.module.ts, ui/src/app/audit/audit-record.service.spec.ts, ui/src/app/audit/audit-record.service.ts, ui/src/app/audit/audit-record/audit-record.component.html, ui/src/app/audit/audit-record/audit-record.component.spec.ts, ui/src/app/audit/audit-record/audit-record.component.ts, ui/src/app/audit/components/audit-record-action/audit-record-action.component.ts, ui/src/app/audit/components/audit-record-action/styles.scss, ui/src/app/audit/components/audit-record-list-bar/audit-record-list-bar.component.html, ui/src/app/audit/components/audit-record-list-bar/audit-record-list-bar.component.ts, ui/src/app/audit/components/audit-record-operation/audit-record-operation.component.ts, ui/src/app/audit/components/audit-record-operation/styles.scss, ui/src/app/audit/components/audit.interface.ts, ui/src/app/layout/navigation/navigation.component.html, ui/src/app/shared/model/audit-record.model.ts, ui/src/app/tests/mocks/audit.ts, ui/src/scss/layout/_content.scss
resolves https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/886
=> gh-886 Add audit-trail support for Streams

ui/package.json
=> Update Flo to 0.8.4 - package.json

ui/src/app/audit/audit-record/audit-record.component.html
=> Audit Records: truncate data column

ui/src/app/tasks/task-execution/task-execution.component.html
=> Task Execution page: fix exit message

ui/src/app/tasks/task-definitions/task-definitions.component.ts
=> Delete schedules menu action: add icon

ui/src/app/about/about/about.component.html
=> Review footer

ui/src/app/tasks/task-definition/executions/task-definition-executions.component.html
=> Task: fix executions pager

ui/src/app/streams/stream-create/create-dialog/create-dialog.component.html, ui/src/app/streams/stream-create/create-dialog/create-dialog.component.spec.ts, ui/src/app/streams/stream-create/create-dialog/create-dialog.component.ts
Fixes #1009 
Remove deploy checkbox and its backend support and tests
=> Remove deploy checkbox from create stream dialog

ui/src/app/jobs/jobs.service.spec.ts, ui/src/app/jobs/jobs.service.ts, ui/src/app/jobs/model/job-execution.model.ts
=> Job Executions list: use thinexecutions endpoint

ui/e2e/protractor.conf.js
=> Update docker Compose URI

ui/src/app/audit/audit-record/audit-record.component.spec.ts
=> Fix unit tests

ui/src/app/about/components/about-more/about-details.component.html, ui/src/app/about/components/about-more/about-details.component.spec.ts, ui/src/app/shared/model/about/feature-info.model.ts, ui/src/app/tests/mocks/about.ts
Update tests
Fix option grafana Enabled
Resolves #1052
=> Update Grafana Options

ui/package.json, ui/src/app/streams/components/flo/support/node-helper.ts, ui/src/app/streams/components/flo/support/shapes.ts
Fixes https://github.com/spring-projects/spring-flo/issues/42 for SCDF UI and a few more fixes for shapes look in FF
=> Flo editor with Firefox improvements

ui/src/app/runtime/runtime-app/runtime-app.component.html, ui/src/app/runtime/runtime-app/runtime-app.component.ts, ui/src/app/shared/grafana/grafana.service.ts, ui/src/app/streams/stream/stream.component.html, ui/src/app/streams/streams/streams.component.ts, ui/src/scss/layout/_table.scss
Added grafana button on an instance app (runtime modal)
Updated grafana button accessibility (streams page)
Fix lint errors
Resolves #1061
=> Polish Grafana Integration

ui/package.json
Flo upgrade for the SCDF UI 2.0 RC
=> Upgrade Flo to 0.8.8

ui/src/app/shared/flo/properties/properties-dialog.component.scss, ui/src/app/streams/components/stream-graph-definition/stream-graph-definition.component.scss
=> Fix SCSS import variables file

ui/src/app/streams/stream-create/stream-create.component.html
=> Stream creation: fix buttons alignment

ui/package.json
=> Update dependency Bootstrap-sass

ui/package.json
=> Pivotal UI dependency: force latest v16

ui/src/app/shared/components/list/list-row-actions.component.ts, ui/src/app/streams/components/flo/text-to-graph.spec.ts, ui/src/app/streams/components/flo/text-to-graph.ts, ui/src/app/tasks/task-launch/task-launch.component.ts
=> Fix Lint errors

ui/src/app/tasks/task-launch/task-launch.component.html
=> Task Launch: update placeholder arguments

ui/src/app/tasks/task-definitions-destroy/task-definitions-destroy.component.ts
Added message error, closed and refresh
Resolves #1097
=> Task Destroy: update behavior on error

ui/src/app/layout/navigation/navigation.component.html, ui/src/app/layout/navigation/navigation.component.ts, ui/src/app/shared/services/shared-about.service.ts
=> gh-1013 Add loading indicator for left navigation

ui/src/app/about/components/about-more/about-details.component.html, ui/src/app/about/components/about-more/about-details.component.spec.ts, ui/src/app/shared/model/about/feature-info.model.ts, ui/src/app/tasks/components/tasks-tabulation/tasks-tabulation.component.html, ui/src/app/tasks/components/tasks-tabulation/tasks-tabulation.component.ts, ui/src/app/tasks/task-definition/task-definition.component.html, ui/src/app/tasks/task-definition/task-definition.component.spec.ts, ui/src/app/tasks/task-definition/task-definition.component.ts, ui/src/app/tasks/task-definitions/task-definitions.component.spec.ts, ui/src/app/tasks/task-definitions/task-definitions.component.ts, ui/src/app/tests/mocks/about.ts
resolves https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1163
=> gh-1163 Change `schedulerEnabled` to `schedulesEnabled`

ui/src/styles.scss
=> Fix SCSS imports priority

ui/src/app/tasks/components/flo/render.service.ts
=> Don't set `.label/text` as it is treated as default label

ui/src/app/tasks/components/flo/support/layout.spec.ts, ui/src/app/tasks/components/flo/support/layout.ts
=> Fix layout case for CT graph where dagre produces bad result

pom.xml, ui/package.json, ui/src/app/streams/stream-deploy/stream-deploy.component.ts
Resolves #1204
Fix bugs:
- The app properties loaded from the DSL should not be submitted
- The sensitive value properties should not be submitted
- Error on showing the app properties modal
=> Stream Deploy: fix ignore properties on deploy

ui/src/app/shared/components/list/list-row-actions.component.ts
=> Fix attribute context menu

ui/src/app/tasks/components/tasks-tabulation/tasks-tabulation.component.ts, ui/src/app/tasks/task-definitions/task-definitions.component.html, ui/src/app/tasks/task-definitions/task-definitions.component.ts, ui/src/app/tasks/task-executions/task-executions.component.html, ui/src/app/tasks/task-executions/task-executions.component.ts, ui/src/app/tasks/task-schedules/task-schedules.component.html, ui/src/app/tasks/task-schedules/task-schedules.component.ts
=> Tasks: force refresh tabs counter on Refresh

.travis.yml
=> Travis Setup: update node version

ui/src/app/tasks/task-definition/executions/task-definition-executions.component.html
=> Task executions page: fix refresh action

ui/src/karma-browserstack.conf.js
- Update browser list config for browserstack unit tests
=> browserstack config

pom.xml
=> Update maven build config

ui/src/app/jobs/jobs/jobs.component.spec.ts, ui/src/app/jobs/jobs/jobs.component.ts, ui/src/app/shared/grafana/grafana.service.ts, ui/src/app/tasks/components/tasks-tabulation/tasks-tabulation.component.html, ui/src/app/tasks/components/tasks-tabulation/tasks-tabulation.component.ts, ui/src/app/tasks/task-definitions/task-definitions.component.spec.ts, ui/src/app/tasks/task-definitions/task-definitions.component.ts, ui/src/app/tasks/task-executions/task-executions.component.spec.ts, ui/src/app/tasks/task-executions/task-executions.component.ts
Resolves #1211
Resolves https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1212
=> Grafana Task buttons

ui/src/app/streams/components/flo/text-to-graph.spec.ts, ui/src/app/streams/components/flo/text-to-graph.ts
=> Fix parser app-property spacing

ui/src/app/streams/streams/streams.component.ts, ui/src/app/tasks/task-definitions/task-definitions.component.ts
=> Update role for destroy selected task

ui/src/app/tasks/task-execution/task-execution.component.html
=> Shorter the task execution cleanup button name

ui/src/app/jobs/job-execution-details/job-execution-details.component.html, ui/src/app/jobs/job-execution-details/job-execution-details.component.ts
=> Job execution: add link to task execution

ui/src/app/tasks/task-schedule-create/task-schedule-create.component.ts
=> Task schedule creation: fix concatenation args

ui/src/app/streams/model/stream-definition.ts, ui/src/app/streams/stream-create/create-dialog/create-dialog.component.html, ui/src/app/streams/stream-create/create-dialog/styles.scss, ui/src/app/tasks/task-definition-create/create-dialog/create-dialog.component.html, ui/src/app/tasks/task-definition-create/create-dialog/styles.scss
=> Review description stream/task feature

ui/src/app/streams/streams/deployment-properties/deployment-properties.component.ts
=> Bulk stream deployment: fix platform field

ui/src/app/apps/app-details/app-details.component.ts
=> Application details page: fix unregister app redirection

ui/src/app/streams/components/stream-graph-definition/stream-graph-definition.component.spec.ts, ui/src/app/streams/model/stream-definition.spec.ts, ui/src/app/streams/model/stream-definition.ts, ui/src/app/streams/streams-deploy/streams-deploy.component.spec.ts, ui/src/app/streams/streams-destroy/streams-destroy.component.spec.ts, ui/src/app/streams/streams-undeploy/streams-undeploy.component.spec.ts, ui/src/app/streams/streams.service.spec.ts, ui/src/app/streams/streams/deployment-properties-info/deployment-properties-info.component.spec.ts, ui/src/app/streams/streams/deployment-properties/deployment-properties.component.spec.ts, ui/src/app/streams/streams/streams.component.html, ui/src/app/streams/streams/streams.component.spec.ts, ui/src/app/tests/mocks/mock-data.ts
- Display `originalDslText` in the stream definition page
- Update tests
Resolves #1286
=> Add originalDslText to stream definition

ui/src/app/streams/streams-utils/streams-import/streams-import.component.html, ui/src/app/tasks/tasks-utils/tasks-import/tasks-import.component.html, ui/src/app/tasks/tasks-utils/tasks-import/tasks-import.component.ts, ui/src/app/tasks/tasks-utils/tasks-utils.service.ts
=> Revisit wording on Tasks/streams utils

ui/src/app/streams/streams-utils/streams-import/streams-import.component.spec.ts, ui/src/app/tasks/tasks-utils/tasks-import/tasks-import.component.spec.ts
=> Fix unit tests scope

ui/src/app/tasks/task-launch/task-launch.component.spec.ts, ui/src/app/tasks/task-launch/task-launch.component.ts, ui/src/app/tasks/task-schedule/task-schedule.component.html, ui/src/scss/components/_tippy.scss, ui/src/scss/components/_toastr.scss
=> Fix toaster style and tab style on schedule page

ui/src/app/streams/stream-create/create-dialog/create-dialog.component.html
=> Stream creation: add truncate pipe to the DSL field

ui/e2e/protractor-saucelabs.conf.js
=> Disabled Safari Browserstack e2e target

ui/src/app/streams/streams/streams.component.html
=> Fix typo Create Stream(s) in the empty stream-list page

README.md
=> Update BrowserStack badge status

ui/src/app/runtime/model/runtime-app.ts
=> Fix lint error

ui/src/app/about/about/about.component.html
=> Update URL documentation API on About page

ui/src/app/tasks/components/flo/metamodel.service.ts, ui/src/app/tasks/components/flo/support/shapes.ts
=> Set proper link ends for Start and End nodes for text->graph

ui/package.json, ui/src/styles.scss
=> Update Flo to 0.9.0. Find flo styles

ui/src/app/apps/components/app-list-bar/app-list-bar.component.html, ui/src/app/apps/components/app-list-bar/app-list-bar.component.ts
=> Fix bulk action on apps page

ui/src/app/streams/components/stream-graph-definition/stream-graph-definition.component.ts
=> Fix dot app instances on Flo Graph

ui/src/app/jobs/jobs/jobs.component.html
=> FIx label in the jobs-list page

ui/src/app/tasks/task-execution/task-execution.component.html
=> Rename Deployment Properties in Platform properties on Task execution

ui/src/app/streams/streams/streams.component.ts
=> Optimize metrics calls on streams list

ui/src/app/audit/audit-record.module.ts, ui/src/app/runtime/model/runtime-app-instance.ts, ui/src/app/runtime/model/runtime-app.ts, ui/src/app/runtime/model/runtime-stream.ts, ui/src/app/runtime/runtime-app/runtime-app.component.spec.ts, ui/src/app/runtime/runtime-app/runtime-app.component.ts, ui/src/app/runtime/runtime-apps.module.ts, ui/src/app/runtime/runtime-apps.service.spec.ts, ui/src/app/runtime/runtime-apps.service.ts, ui/src/app/runtime/runtime-apps/runtime-apps.component.html, ui/src/app/runtime/runtime-apps/runtime-apps.component.spec.ts, ui/src/app/runtime/runtime-apps/runtime-apps.component.ts, ui/src/app/runtime/runtime-apps/styles.scss, ui/src/app/tests/mocks/mock-data.ts, ui/src/app/tests/mocks/runtime.ts
=> Revisit runtimes page

ui/src/app/tasks/task-launch/task-launch.component.ts
=> Load parameters on re-launch a task

ui/src/app/tasks/tasks.service.ts
=> Add platform name argument to retrieve task logs

ui/package.json, ui/src/app/flo/shared/flo.scss, ui/src/app/flo/shared/service/doc.service.ts, ui/src/app/flo/shared/support/node-component.ts, ui/src/app/flo/stream-flo.module.ts, ui/src/app/flo/stream/node/stream-node.component.html, ui/src/app/flo/stream/node/stream-node.component.ts, ui/src/app/flo/task-flo.module.ts, ui/src/app/flo/task/node/task-node.component.html, ui/src/app/flo/task/node/task-node.component.ts, ui/src/app/shared/directive/tippy.directive.ts, ui/src/app/shared/pipe/capitalize.pipe.ts, ui/src/app/shared/shared.module.ts, ui/src/styles.scss
Fixes #1424 
Tippy directive. Use tippy directive for tooltips for various parts of Flo node shape
=> Tippy for Flo nodes

ui/src/app/flo/shared/properties/properties-dialog.component.ts, ui/src/app/flo/stream/node/stream-node.component.html, ui/src/app/flo/stream/node/stream-node.component.ts, ui/src/app/flo/stream/properties/stream-properties-dialog.component.ts, ui/src/app/flo/task/node/task-node.component.html, ui/src/app/flo/task/node/task-node.component.ts, ui/src/app/flo/task/properties/task-properties-dialog-component.ts
Properties dialog working with Clarity lib
Fixes #1422
=> Adopt Clarity for App Properties Dialog

ui/src/app/flo/shared/service/parser.service.ts, ui/src/app/flo/shared/service/parser.spec.ts, ui/src/app/flo/shared/service/parser.ts, ui/src/app/streams/streams.module.ts, ui/src/app/streams/streams/stream-dsl/stream-dsl.component.html, ui/src/app/streams/streams/stream-dsl/stream-dsl.component.scss, ui/src/app/streams/streams/stream-dsl/stream-dsl.component.ts, ui/src/app/streams/streams/stream/stream.component.html
Fixes #1428 
Needs feedback for the implementation as a component and styling.
Currently new component applied only to stream list DSL column.
(More to be switched later once implementation settles)
@oodamien looking for your feedback
=> Short DSL UI

ui/src/app/shared/flo/flo.scss, ui/src/app/streams/stream/history/stream-history.component.html, ui/src/scss/components/_forms.scss, ui/src/scss/layout/_sidebar.scss, ui/src/scss/layout/_table.scss, ui/src/scss/styles.scss
=> Fix icons alignment

ui/package.json, ui/src/app/shared/flo/support/shared-shapes.ts, ui/src/app/streams/components/flo/support/shapes.ts
Fix shapes module loading issues in prod such as:
```
Uncaught TypeError: Cannot set property 'DataflowPaletteGroupHeader' of undefined
at Module.zUnb (main-es2015.5095faa41d8d817ba40a.js:1)
at l (runtime-es2015.c9afb3256f2870e161de.js:1)
at Object.0 (main-es2015.5095faa41d8d817ba40a.js:1)
at l (runtime-es2015.c9afb3256f2870e161de.js:1)
at t (runtime-es2015.c9afb3256f2870e161de.js:1)
at Array.r [as push] (runtime-es2015.c9afb3256f2870e161de.js:1)
```
=> Load shapes function

ui/package.json, ui/src/app/flo/stream/editor.service.spec.ts, ui/src/app/flo/stream/editor.service.ts, ui/src/app/flo/stream/node-helper.service.ts, ui/src/app/flo/stream/render.service.ts, ui/src/app/flo/stream/support/utils.spec.ts, ui/src/app/flo/stream/text-to-graph.ts
Fixes #1457 for the master branch
=> Replace selector at the link end with magnet

ui/package.json, ui/src/app/streams/components/flo/editor.service.spec.ts, ui/src/app/streams/components/flo/editor.service.ts, ui/src/app/streams/components/flo/node-helper.service.ts, ui/src/app/streams/components/flo/render.service.ts, ui/src/app/streams/components/flo/support/utils.spec.ts, ui/src/app/streams/components/flo/text-to-graph.ts
=> Replace link end selector with magnet

ui/src/app/streams/components/flo/sanitize-dsl.service.ts, ui/src/app/streams/stream-create/create-dialog/create-dialog.component.spec.ts, ui/src/app/streams/stream-create/create-dialog/create-dialog.component.ts, ui/src/app/streams/streams.module.ts
Extract static function to call to angular service function
=> Sanitize DSL service

ui/src/app/flo/stream-flo.module.ts, ui/src/app/flo/stream/dsl-sanitize.service.ts, ui/src/app/streams/streams/create/create.component.spec.ts, ui/src/app/streams/streams/create/create.component.ts
=> Factor out DSL text parsing into single streams into a service 

ui/src/app/shared/service/import-export.service.ts, ui/src/app/streams/streams/deploy/stream-deploy.service.ts, ui/src/app/streams/streams/stream/stream.component.ts
=> Use ParserService rather than Parser.parse(...)

ui/src/app/tasks/task-execution/task-execution.component.ts
=> Update condition to get logs on task execution details

ui/angular.json, ui/package.json, ui/src/app/flo/shared/support/node-component.ts, ui/src/app/flo/shared/support/utils.ts, ui/src/app/flo/stream/component/create.component.ts, ui/src/app/flo/stream/component/runtime-view.component.spec.ts, ui/src/app/flo/stream/component/runtime-view.component.ts, ui/src/app/flo/stream/editor.service.spec.ts, ui/src/app/flo/stream/editor.service.ts, ui/src/app/flo/stream/graph-to-text.spec.ts, ui/src/app/flo/stream/graph-to-text.ts, ui/src/app/flo/stream/properties-editor.service.ts, ui/src/app/flo/stream/properties/stream-properties-source.ts, ui/src/app/flo/stream/render.service.ts, ui/src/app/flo/stream/support/utils.ts, ui/src/app/flo/task/component/create.component.ts, ui/src/app/flo/task/editor.service.spec.ts, ui/src/app/flo/task/editor.service.ts, ui/src/app/flo/task/metamodel.service.ts, ui/src/app/flo/task/node/task-node.component.ts, ui/src/app/flo/task/properties/task-properties-source.ts, ui/src/app/flo/task/render.service.ts, ui/src/app/flo/task/support/layout.ts, ui/src/app/shared/api/app.service.ts
=> Move apps metadata from Element#attr(...) to Element#prop(...)

ui/package.json, ui/src/app/flo/stream/render.service.ts
=> Fixes for tap links and default app name

ui/src/app/apps/apps-add/apps-add.validator.spec.ts, ui/src/app/apps/apps-add/apps-add.validator.ts
=> Update Bulk import application validators

ui/src/app/shared/model/platform.ts, ui/src/app/tasks/components/schedules-list-bar/schedules-list-bar.compontent.ts, ui/src/app/tasks/components/tasks.interface.ts, ui/src/app/tasks/model/task-schedule.ts, ui/src/app/tasks/task-definition/schedules/task-definition-schedules.component.spec.ts, ui/src/app/tasks/task-definition/schedules/task-definition-schedules.component.ts, ui/src/app/tasks/task-definition/task-definition.component.html, ui/src/app/tasks/task-definition/task-definition.component.ts, ui/src/app/tasks/task-definitions/task-definitions.component.ts, ui/src/app/tasks/task-schedule-create/task-schedule-create.component.html, ui/src/app/tasks/task-schedule-create/task-schedule-create.component.spec.ts, ui/src/app/tasks/task-schedule-create/task-schedule-create.component.ts, ui/src/app/tasks/task-schedules-destroy/task-schedules-destroy.component.html, ui/src/app/tasks/task-schedules-destroy/task-schedules-destroy.component.spec.ts, ui/src/app/tasks/task-schedules/task-schedules.component.html, ui/src/app/tasks/task-schedules/task-schedules.component.spec.ts, ui/src/app/tasks/task-schedules/task-schedules.component.ts, ui/src/app/tasks/tasks.module.ts, ui/src/app/tasks/tasks.service.spec.ts, ui/src/app/tasks/tasks.service.ts, ui/src/app/tests/mocks/mock-data.ts, ui/src/scss/layout/_content.scss
=> Add platforms support for schedules

ui/src/app/tasks/components/flo/metamodel.service.ts
=> Adjust for metadata not under attrs

ui/src/app/shared/service/logger.service.ts
Mirror #1500 for master branch
=> Use isDevMode() instead of environment

ui/src/app/streams/components/flo/node-helper.service.ts
Fix tap shape port. Currently it has an input port instead of an output port
DSL: `:s1.something > jdbc`
=> Tap should have one output port

ui/src/app/flo/shared/support/shared-shapes.ts, ui/src/app/flo/stream/editor.service.ts, ui/src/app/flo/stream/metamodel.service.ts, ui/src/app/flo/stream/properties-editor.service.ts, ui/src/app/flo/stream/render.service.ts, ui/src/app/flo/stream/support/shapes.ts
=> API polish

ui/src/app/flo/shared/support/view-utils.ts, ui/src/app/flo/stream/render.service.spec.ts, ui/src/app/flo/stream/render.service.ts
=> Truncate label for stream names

ui/src/app/flo/shared/service/parser.ts
=> Avoid logging to error for parser errors

ui/src/app/shared/api/stream.service.spec.ts, ui/src/app/shared/api/stream.service.ts, ui/src/app/streams/streams/deploy/builder/builder.component.ts, ui/src/app/streams/streams/deploy/deploy.component.ts, ui/src/app/streams/streams/multi-deploy/multi-deploy.component.ts, ui/src/app/streams/streams/stream-deploy.service.spec.ts, ui/src/app/streams/streams/stream-deploy.service.ts, ui/src/app/tests/service/app.service.mock.ts, ui/src/app/tests/service/stream-deploy.service.mock.ts, ui/src/app/tests/service/stream.service.mock.ts
=> Re-use deployment properties post undeploy

ui/src/app/tasks-jobs/jobs/execution/execution.component.html
=> Fix job execution link to step

ui/src/app/tasks-jobs/schedules/create/create.component.ts
=> Close modal loading on schedule creation error

ui/src/app/flo/shared/flo.scss
=> Crosshair cursor for link creation area (magnet shape)

ui/src/app/flo/shared/support/view-utils.ts
Joint utility attempts to break text to display in multiple lines and needs a finite height parameter to not to break the label in multiple lines. If hight == label text height it may end up without any text. Only multiplying by 1.1 helped (1.05 did not). Therefore, best to use our own utility - faster and more control over.
=> Use own utility to truncate label text

ui/src/app/apps/apps.component.html, ui/src/app/apps/apps.component.spec.ts, ui/src/app/manage/records/records.component.html, ui/src/app/manage/records/records.component.spec.ts, ui/src/app/shared/component/datagrid/datagrid.component.ts, ui/src/app/shared/pipe/datagrid-column.pipe.ts, ui/src/app/shared/shared.module.ts, ui/src/app/shared/store/context.reducer.ts, ui/src/app/streams/streams/streams.component.html, ui/src/app/streams/streams/streams.component.spec.ts, ui/src/app/tasks-jobs/executions/executions.component.html, ui/src/app/tasks-jobs/executions/executions.component.spec.ts, ui/src/app/tasks-jobs/jobs/jobs.component.html, ui/src/app/tasks-jobs/jobs/jobs.component.spec.ts, ui/src/app/tasks-jobs/schedules/schedules.component.html, ui/src/app/tasks-jobs/schedules/schedules.component.spec.ts, ui/src/app/tasks-jobs/tasks/tasks.component.html, ui/src/app/tasks-jobs/tasks/tasks.component.spec.ts, ui/src/scss/styles.scss
=> Revisit default size column datagrid

ui/package.json, ui/src/styles.scss
Point to the latest released Flo lib
=> Upgrade Flo to 0.10.1

ui/src/app/streams/streams/stream-deploy.service.ts
=> Hide instance count option in Stream Update

ui/package.json, ui/src/styles.scss
Switch to Flo from master which has dependencies updated
=> Flo to Angular 11

ui/src/app/streams/streams.module.ts, ui/src/app/streams/streams/clone/clone.component.html, ui/src/app/streams/streams/clone/clone.component.spec.ts, ui/src/app/streams/streams/clone/clone.component.ts, ui/src/app/streams/streams/streams.component.html, ui/src/app/streams/streams/streams.component.ts, ui/src/app/tasks-jobs/tasks-jobs.module.ts, ui/src/app/tasks-jobs/tasks/clone/clone.component.html, ui/src/app/tasks-jobs/tasks/clone/clone.component.spec.ts, ui/src/app/tasks-jobs/tasks/clone/clone.component.ts, ui/src/app/tasks-jobs/tasks/tasks.component.html, ui/src/app/tasks-jobs/tasks/tasks.component.ts
=> Stream / Task clone

README_DEV.md, ui/src/app/shared/component/search/search.component.html, ui/src/app/shared/component/search/search.component.spec.ts, ui/src/app/shared/component/search/search.component.ts
=> Fix for search for disabled features

ui/src/app/streams/streams/deploy/builder/builder.component.html, ui/src/app/streams/streams/deploy/builder/builder.component.scss, ui/src/app/tests/service/notification.service.mock.ts
=> FIx builder deploy validation

ui/src/app/apps/app/app.component.html, ui/src/app/apps/apps.component.html, ui/src/app/apps/unregister/unregister.component.html, ui/src/app/apps/unregister/unregister.component.spec.ts, ui/src/app/streams/streams/destroy/destroy.component.html, ui/src/app/streams/streams/destroy/destroy.component.spec.ts, ui/src/app/streams/streams/streams.component.html, ui/src/app/tasks-jobs/executions/cleanup/cleanup.component.html, ui/src/app/tasks-jobs/executions/cleanup/cleanup.component.spec.ts, ui/src/app/tasks-jobs/executions/execution/execution.component.html, ui/src/app/tasks-jobs/executions/executions.component.html, ui/src/app/tasks-jobs/schedules/destroy/destroy.component.html, ui/src/app/tasks-jobs/schedules/destroy/destroy.component.spec.ts, ui/src/app/tasks-jobs/schedules/schedule/schedule.component.html, ui/src/app/tasks-jobs/schedules/schedules.component.html, ui/src/app/tasks-jobs/tasks/destroy/destroy.component.html, ui/src/app/tasks-jobs/tasks/destroy/destroy.component.spec.ts, ui/src/app/tasks-jobs/tasks/task/task.component.html, ui/src/app/tasks-jobs/tasks/tasks.component.html
Revisit colors for: app unregister, stream destroy, task destroy, execution clean up, schedule destroy
Resolves #1632
=> Update buttons action styles

ui/src/app/shared/component/search/search.component.spec.ts, ui/src/app/shared/component/search/search.component.ts, ui/src/app/tasks-jobs/schedules/schedules.component.ts
=> Schedules page to show error message on 500x errors

ui/src/app/tasks-jobs/tasks/launch/builder/builder.component.html
- Calculate better index ordering so that we can
tab and move left to right and top to bottom.
- Fixes #1645
=> Fix tabindex numbers in task launch

ui/src/app/tasks-jobs/executions/execution/execution.component.html, ui/src/app/tasks-jobs/jobs/execution/execution.component.html, ui/src/app/tasks-jobs/jobs/step/step.component.html, ui/src/app/tasks-jobs/tasks/task/task.component.html
- Fix how platform properties are shown with executions for
task/batch as this broken in templates when underlaying
structure were changed to be more type safe.
- Fixes #1661
=> Fix showing tasks platform properties

ui/src/app/tasks-jobs/jobs/jobs.component.ts
=> Backporting error handling.

ui/src/app/tasks-jobs/tasks/launch/free-text/free-text.component.html
=> Launch button name on Freetext matches name on builder tab.

ui/src/app/shared/api/schedule.service.ts
=> Adds platform information to schedule lists and task definition detail

ui/src/app/tasks-jobs/tasks/launch/launch.component.html, ui/src/app/tasks-jobs/tasks/launch/launch.component.ts
- Same way as stream deploy, blocking modal
when launch happens.
- Fixes #1680
=> Add modal to task launch

ui/src/app/apps/version/version.component.html
=> Revisit word wrap on Manage Version Modal

ui/src/app/streams/runtime/details/details.component.scss
=> Add `background` on `Stream > Runtime > Detail > Input` 

ui/src/app/streams/streams/status/status.component.ts
=> Fix stream status modal help

ui/src/app/tasks-jobs/tasks/launch/builder/builder.component.ts
Fixes https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1685
=> No property validation for additional task arguments

ui/src/app/tasks-jobs/schedules/create/create.component.html
=> Update helper description on Schedule creation page

ui/src/app/manage/tools/cleanup/cleanup.component.html, ui/src/app/manage/tools/tools.component.html, ui/src/app/shared/api/task.service.ts
Wording Clean up Task execution(s)
Fix Task Executions Count URL
Resolves #1727
=> Fix Clean Up Tools

ui/src/app/flo/shared/properties-groups/properties-groups-dialog.component.ts, ui/src/app/flo/shared/properties/properties-dialog.component.ts, ui/src/app/flo/shared/support/properties-group-model.ts
=> Update conditions on properties modal filtering

ui/src/app/tasks-jobs/tasks/create/create.component.html, ui/src/app/tasks-jobs/tasks/create/create.component.ts
=> Fix redirection on cancel task creation

ui/src/app/tasks-jobs/tasks/launch/builder/builder.component.ts
=> Fix warning on Launch page

ui/src/app/shared/component/search/search.component.ts
=> Force only default version on applications quick search

ui/src/app/apps/app/app.component.html, ui/src/app/apps/app/app.component.ts, ui/src/scss/styles.scss
See https://github.com/spring-cloud/spring-cloud-dataflow/issues/3815
=> Show id instead of name on App view

ui/package-lock.json, ui/package.json, ui/src/styles.scss
=> Upgrade Flo to 0.11.0

ui/src/app/streams/streams/deploy/free-text/free-text.component.scss, ui/src/app/tasks-jobs/tasks/launch/free-text/free-text.component.scss
=> Fix textarea line height on Launch task and deploy stream page

ui/src/app/flo/shared/support/app-metadata.ts, ui/src/app/flo/shared/support/app-ui-property.ts, ui/src/app/flo/shared/support/graph-node-properties-source.ts
A property can belong to more than one group.
=> Multiple groups for a an app property

ui/.eslintrc.json, ui/angular.json, ui/e2e/src/app.e2e-spec.ts, ui/e2e/src/page/apps/apps.po.ts, ui/e2e/src/page/manage/import-export.po.ts, ui/e2e/src/page/manage/records.po.ts, ui/e2e/src/page/streams/list.po.ts, ui/e2e/src/page/streams/runtime.po.ts, ui/e2e/src/page/tasks-jobs/executions.po.ts, ui/e2e/src/page/tasks-jobs/job-executions.po.ts, ui/e2e/src/page/tasks-jobs/tasks.po.ts, ui/e2e/src/utils/element.helper.ts
Fix linter issue
Disable eslint indent
Resolves #1780 #1777
=> Update linter configuration

ui/src/app/shared/model/task.model.ts, ui/src/app/tasks-jobs/tasks/launch/builder/builder.component.html, ui/src/app/tasks-jobs/tasks/launch/builder/builder.component.ts, ui/src/app/tasks-jobs/tasks/launch/task-launch.service.ts
Show a specific message on the app version field (Last launch version)
Resolves #1779
=> Update version label on Task Launch page

ui/src/app/streams/streams/create/create.component.html, ui/src/app/tasks-jobs/tasks/create/create.component.html
=> fix: Streams/tasks create modal

ui/src/app/tasks-jobs/executions/execution/execution.component.ts, ui/src/app/tasks-jobs/jobs/execution/execution.component.ts, ui/src/app/tasks-jobs/tasks/task/task.component.ts
=> fix: Update viewLog accessibility on task page

ui/src/app/streams/streams/scale/scale.component.html, ui/src/app/streams/streams/scale/scale.component.ts
Update scale instance limit to 10000.
Resolves #1821
=> Update scale instances limit

ui/src/app/flo/task/component/create.component.ts, ui/src/app/streams/streams/deploy/builder/builder.component.html
=> Adjust missing translations

ui/package-lock.json, ui/src/app/shared/api/task.service.ts
Added encoding feature in task launch service.
Resolves #1808 and https://github.com/spring-cloud/spring-cloud-dataflow/issues/4728.
=> Encoding on task launch service

ui/package-lock.json, ui/src/app/about/info/info.component.scss, ui/src/app/about/info/info.component.ts, ui/src/app/layout/nav/nav.component.html, ui/src/app/tasks-jobs/executions/execution/execution.component.ts, ui/src/app/tasks-jobs/jobs/execution/execution.component.ts, ui/src/app/tasks-jobs/tasks/task/task.component.ts
=> Backport 3.2.x

ui/src/app/streams/streams/streams.component.spec.ts, ui/src/app/streams/streams/streams.component.ts, ui/src/app/tasks-jobs/executions/executions.component.spec.ts, ui/src/app/tasks-jobs/executions/executions.component.ts, ui/src/app/tasks-jobs/tasks/tasks.component.spec.ts, ui/src/app/tasks-jobs/tasks/tasks.component.ts
=> Feat: Add error message on streams/tasks/executions pages

ui/cypress/integration/streams.spec.ts
Add e2e cypress tests for scale functionality.
Resolves #1832
=> E2E tests for scaling streams

ui/src/app/tasks-jobs/tasks/task/task.component.html, ui/src/assets/i18n/en.json
=> Optimize task complete status on task details page

ui/cypress/integration/streams.spec.ts
=> Resolve linter

ui/src/app/settings/settings/settings.component.html
=> Solve selected language option

ui/src/app/settings/settings/settings.component.html
=> Resolve settings overlapping text

ui/src/assets/i18n/de.json, ui/src/assets/i18n/en.json
=> fix: missing translation on Step Execution job

ui/src/app/tasks-jobs/executions/executions.component.html
=> fix: inconsistent on task executions

ui/src/logout-success-oauth.html
=> fix: Remove bootstrap from logout page

ui/src/logout-success-oauth.html
* Backport of https://github.com/spring-cloud/spring-cloud-dataflow-ui/commit/c465d04acbb00d4df0b1d3f4fe2d353ad664d3d6
Resolves #1871
=> Remove bootstrap from logout page (backport #1867)

ui/src/app/shared/api/task.service.ts, ui/src/app/tasks-jobs/tasks/task/task.component.ts
=> Prevent undefined on http task execution request

ui/src/app/apps/add/props/props.component.html, ui/src/app/shared/component/key-value/key-value.component.scss
=> Solve responsive behaviour on add applications (props) for label and textarea

ui/src/assets/i18n/de.json, ui/src/assets/i18n/en.json
=> fix: add missing translation

ui/src/app/manage/tools/stream/import.component.ts, ui/src/app/manage/tools/task/import.component.ts
Resolves #1798 
Added status colors on icons for 
- Tools > Import streams
- Tools > Import tasks 
modal components.
=> Style clarity colors on import streams / tasks

ui/src/app/shared/model/task-execution.model.ts, ui/src/app/tasks-jobs/executions/executions.component.html
=> Visualize status indicator on tasks executions

ui/src/app/manage/tools/stream/import.component.ts, ui/src/app/manage/tools/task/import.component.ts
Use `Close` instead of `Cancel`
See Stream(s) and Task(s) import
Resolves #1886
=> Update importing modal close action

ui/src/app/tasks-jobs/executions/executions.component.html
Resolves 
- #1904  
- https://github.com/spring-cloud/spring-cloud-dataflow/issues/5183
=> Update task executions status property

.github/settings.xml, pom.xml
See https://github.com/spring-cloud/spring-cloud-dataflow/issues/5193
=> Add MavenCentral in place of repo.spring.io/release (#101)

ui/src/app/manage/tools/task/export.component.ts, ui/src/app/shared/api/task.service.spec.ts, ui/src/app/shared/api/task.service.ts, ui/src/app/shared/component/search/search.component.ts, ui/src/app/tasks-jobs/tasks/tasks.component.html, ui/src/app/tasks-jobs/tasks/tasks.component.ts, ui/src/app/tests/api/task.service.mock.ts
Frontend implementation for: https://github.com/spring-cloud/spring-cloud-dataflow/issues/5294#issuecomment-1549828455
Needs to be integrated with: https://github.com/spring-cloud/spring-cloud-dataflow/pull/5344
Unfiltered:
Filtered for description:
Filtered for description and taskName:
=> feat: filter for task description and dslText

pom.xml
Due to some warnings I upgraded the maven plugins and added a property for the encoding.
=> feat: plugins upgrades

ui/src/app/shared/api/task.service.spec.ts, ui/src/app/shared/api/task.service.ts, ui/src/app/tasks-jobs/executions/cleanup/cleanup.component.ts
=> Adjust task executions group deletion

ui/src/app/tasks-jobs/executions/executions.component.html
=> Disable sort on schema target column temporarily 

ui/src/app/tasks-jobs/jobs/step/step.component.html
=> Remove attributes on Step execution

ui/src/app/apps/app/app.component.html, ui/src/app/apps/app/app.component.ts
=> Details panel selected app version

ui/src/scss/styles.scss
=> Menu style on low screens resolutions

ui/src/app/apps/add/uri/uri.component.html
=> fix: Update label on importing apps

ui/src/app/tasks-jobs/tasks/task-prop.validator.spec.ts, ui/src/app/tasks-jobs/tasks/task-prop.validator.ts
=> Update task schedule validator

ui/src/assets/i18n/de.json
I found two wrong words in the german translation and fixed them.
=> fix typos in de.json

ui/src/app/apps/apps.component.html, ui/src/scss/styles.scss
=> Truncate version on Apps list

.github/workflows/release-worker.yml
See https://github.com/spring-cloud/spring-cloud-dataflow/issues/5584
=> Use new private release repo libs-release-staging

ui/src/app/tasks-jobs/executions/execution/log/log.component.ts, ui/src/scss/styles.scss
=> fix: log scrolls visibility

pom.xml
=> feat: Update node.JS v1.18 LTS

ui/src/app/app.module.ts, ui/src/app/shared/api/task.service.spec.ts, ui/src/app/shared/api/task.service.ts, ui/src/app/shared/model/task-execution.model.ts
=> Update task execution list

ui/src/app/tasks-jobs/tasks/launch/builder/builder.component.html, ui/src/app/tasks-jobs/tasks/launch/builder/builder.component.ts
Hide Default version on app if a version has been selected
=> feat: Update task launch builder

.github/workflows/build-snapshot-worker.yml, .github/workflows/ci.yml
Updates JFrog action to v3
Updates JFrog maven configuration to use JS_SERVER_ID repository variable.
=> Update JFrog action to v3

README.md
Badges for tools that are no longer in use are to be removed.
=> Remove old badges from UI README page
