- ui/app/scripts/stream/views/definition-deploy.html
* Link points now to: http://docs.spring.io/spring-cloud-dataflow/docs/current-SNAPSHOT/reference/htmlsingle/#_passing_application_properties_when_deploying_stream
Resolves spring-cloud/spring-cloud-dataflow-ui#97
> gh-97 Deploy Stream Definition - Change Doc Link

- ui/app/scripts/app/controllers.js
- ui/app/scripts/app/controllers/apps.js
- ui/app/scripts/app/controllers/bulk-import-apps.js
- ui/app/scripts/app/services.js
- ui/app/scripts/app/views/apps-list.html
- ui/app/scripts/app/views/bulk-import-apps.html
- ui/app/scripts/directives.js
- ui/app/scripts/routes.js
* Add support to point to http resources
* Add support to paste apps (properties) into a text-area field
* Using a fileupload button, add the ability to load apps properties via a text-file
* Add one-click ability to register out-of-the-box app starters (Stream + Task)
Resolves https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/48
> gh-48 Implement bulk import of apps

- ui/app/index.html
- ui/app/logout-success-oauth.html
- ui/app/scripts/auth/controllers/login.js
- ui/app/scripts/auth/controllers/logout.js
- ui/app/scripts/auth/services.js
- ui/app/scripts/main.js
- ui/bower.json
Depends on https://github.com/spring-cloud/spring-cloud-dataflow/pull/897
Resolves https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/118
> gh-118 Add form-based non-oauth login page

- ui/app/scripts/stream/controllers/create-streams-dialog.js
Without this I think the create button on the Create Streams page is broken (please verify that before you apply). It will open the dialog but then fail because it is looking for the streams parser (when it is now a shared parser). With this change in place it will find the right thing and succeed.
We don't have enough automated tests around that UI.
> Fix reference from StreamParserService to shared ParserService

- ui/package.json
Build of SCDF-UI fails on Mac OSX Sierra because tests fail to launch. PhantomJS fails to start hence none of the tests run.
PhantomJS related tooling packages need to be upgraded.
> Update phantomjs tooling to run on osx sierra

- ui/app/scripts/analytics/views/counters.html
- ui/app/scripts/analytics/views/dashboard.html
- ui/app/scripts/analytics/views/gauges.html
- ui/app/scripts/analytics/views/rich-gauges.html
- ui/app/scripts/app/views/apps-list.html
- ui/app/scripts/job/views/execution-details.html
- ui/app/scripts/job/views/executions.html
- ui/app/scripts/runtime/views/runtime-apps-list.html
- ui/app/scripts/stream/controllers/definitions.js
- ui/app/scripts/stream/services.js
- ui/app/scripts/stream/views/definitions.html
- ui/app/scripts/task/controllers/definitions.js
- ui/app/scripts/task/services.js
- ui/app/scripts/task/views/definitions.html
- ui/app/scripts/task/views/executions.html
* Add server-backed filtering to Stream and Task definition list pages
* Remove client-side filtering
Resolves https://github.com/spring-cloud/spring-cloud-dataflow/issues/854
Resolves spring-cloud/spring-cloud-dataflow-ui#137
Depends on PR https://github.com/spring-cloud/spring-cloud-dataflow/pull/987
> server-gh-235 Improve search capability in the list pages

- ui/app/scripts/app/controllers/bulk-import-apps.js
- ui/app/scripts/shared/views/about.html
- pointing shell download to 'libs-snapshot' repo to resolve release, milestone amd snapshot artifacts
- updating app resources to use Avogadto.SR1 and Addison.GA
> Quick fix for download links

- ui/src/app/about/about.component.ts
- ui/src/app/analytics/analytics.component.ts
- ui/src/app/app.component.ts
- ui/src/app/apps/apps.component.ts
- ui/src/app/jobs/jobs.component.ts
- ui/src/app/runtime/runtime.component.ts
- ui/src/app/streams/stream-create/stream-create.component.ts
- ui/src/app/streams/stream-definitions/stream-definitions.component.ts
- ui/src/app/streams/streams.component.ts
- ui/src/app/tasks/tasks.component.ts
Originally were place holders that are no longer necessary
> Removing unnecessary Sassy CSS files.

- ui/app/scripts/app/controllers/apps.js
- ui/app/scripts/app/views/apps-list.html
- This change doesn't show up in the UI by default as the current page size is set to 60
- But this PR is required as the apps list REST controller returns paginated list now
Resolves #240
> Paginate apps list page

- ui/src/app/streams/stream-definitions/stream-definitions.component.html
- ui/src/app/streams/stream-definitions/stream-definitions.component.ts
- Disabling button if stream is currently deployed
or deploying.
- From js methods remove second index parameters
which is undefined in template.
- Fixes #255
> Fix deploying button visibility

- ui/src/app/about/about-details.component.html
- ui/src/app/tasks/task-definitions/task-definitions.component.html
- ui/src/app/tasks/task-details/task-details.component.html
* Removes the status column in task definition page.  The missing popup was missing and when researching what was to be put in it, it was incorrect in the 1.2.x line.  And since task status  made no sense in the previous release nor here so it was removed.
* Removed code to retrieve job execution ids since it is not implemented in the class.
* Used a for loop to populate the platform specific information in the about detail.  Please review this for style, took a swag at what we wanted.
resolves #319
> Resolves bugs identified in lint.

- ui/src/styles.scss
- Changing table-layout from fixed back to default
auto which is set by PUI. Fixed layout just doesn't
seem to work overall if seeing all tables we use,
ecpecially when narrowing browser size.
- While fixed might be better in some cases, we should
not use it until we know better settings which
works with all tables.
- Fixes #359
> Change table layout css

- README.md
The current badge is showing SCDF's core code-coverage stats instead of the UI project. This change fixes the bogus badge and also the link launches the `master` branch stats by default.
> Fix the bogus codecov badge

- ui/src/app/streams/flo/support/utils.spec.ts
- ui/src/app/streams/flo/support/utils.ts
- ui/src/app/streams/stream-create/stream-create-dialog.component.html
- ui/src/app/streams/stream-create/stream-create-dialog.component.scss
- ui/src/app/streams/stream-create/stream-create-dialog.component.ts
Validate against duplicate names on the form
Fixes #402 
If "Create stream dialog" has duplicate stream names on the from validation error should be displayed under the form controls having duplicate names
> Validate against duplicate stream names on the form

- ui/src/app/streams/streams.service.spec.ts
- ui/src/app/streams/streams.service.ts
- Ensure that we send the respective default headers:
* `Content-Type`: `application/json`
* `Accept`: `application/json`
- Fix tests
resolves https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/455
> gh-455 Fix: Stream fails to deploy with security enabled

- ui/src/app/streams/flo/render.service.ts
- ui/src/app/streams/stream-graph-view/stream-graph-view.component.spec.ts
Make Render service compatible with PhantomJS. Should allow for more complex tests. Made one test a bit more complex.
> Make rendering PhantomJS compatible to run complex tests

- ui/src/app/analytics/dashboard/dashboard.component.html
- ui/src/app/analytics/dashboard/dashboard.component.ts
- ui/src/app/analytics/model/dashboard-item.model.ts
* Make the counter collection part of each `DashboardItem`
resolves https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/459
> gh-459 Fix: Analytics - Adding a second counter resets name in first graph

- ui/.angular-cli.json
- ui/proxy.conf.json
- ui/src/app/auth/auth.service.ts
- ui/src/app/auth/logout.component.ts
- ui/src/logout-success-oauth.html
* Add Logout success page
* Add logout functionality (Differentiate between traditional logouts and OAuth2 logouts)
-> For testing with UAA https://gist.github.com/ghillert/5f2fba0ee412f8e82c86daf59e610c12
resolves https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/368
> gh-368 Migrate OAuth2 UI Security

- ui/proxy.conf.json
- ui/src/app/tasks/flo/editor.service.ts
- ui/src/app/tasks/flo/metamodel.service.ts
- ui/src/app/tasks/flo/node/node.component.html
- ui/src/app/tasks/flo/node/node.component.scss
- ui/src/app/tasks/flo/node/node.component.ts
- ui/src/app/tasks/flo/render.service.ts
- ui/src/app/tasks/flo/support/shapes.ts
- ui/src/app/tasks/flo/task-graph-view/task-graph-view.component.html
- ui/src/app/tasks/flo/task-graph-view/task-graph-view.component.spec.ts
- ui/src/app/tasks/flo/task-graph-view/task-graph-view.component.ts
- ui/src/app/tasks/task-create-composed-task/task-create-composed-task.component.html
- ui/src/app/tasks/task-create-composed-task/task-create-composed-task.component.ts
- ui/src/app/tasks/tasks.module.ts
- Focus for this is to copy and implement tasks
editors without touching any flo code in streams.
Essentially this is to get dsl and flo editor to
work on some level. Some error are still expected
which will get fixed in other PR's.
- When tasks flo is closer to its full implementation,
then it's easier to see what is the actual shared
feature set in tasks and streams and extract that
to shared classes. For this specific reason I'm
referensing some stream flo classes from tasks.
- I'm starting to add tests in PR's after this.
- There has been some attempt to not use stuff under
`joint.shapes.flo` directly as it will create situation
where typescript compiles but may result runtime
errors if some specific imports are missing.
- Fixes #484
> Initial infra for composed tasks

- ui/src/app/analytics/analytics.service.spec.ts
- ui/src/app/analytics/analytics.service.ts
- In AnalyticsService check if given rate is undefined
istead of simple `if(rate) as that will be false if
zero is given.
- Add spec for AnalyticsService and test intervals.
- Imports polish for AnalyticsService
- Fixes #418
> Fix analytics polling stop

- ui/src/app/streams/flo/editor.service.ts
- ui/src/app/streams/flo/graph-to-text.spec.ts
- ui/src/app/streams/flo/graph-to-text.ts
- ui/src/app/streams/stream-create/stream-create.component.ts
With this change the validation of properties now works
properly in the DSL view when creating streams. There are a
few changes included:
- use map access to get ranges rather than property access.
- use hasOwnProperty to verify severity specified otherwise
markers with severity 0 are filtered out.
- when building the text from the graph, update the graph
propertiesranges to indicate where the properties have
been put in the DSL text.
Fixes #482
> Ensure ranges set for properties and they are used correctly

- ui/src/app/apps/apps.component.html
- ui/src/app/auth/directives/roles.directive.ts
* Render a message similar to the old UI.
* Make the message role aware
- `Register Application(s)` button is only shown if user has the `CREATE` role
resolves https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/499
See also screenshots added under https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/499
> gh-499 Provide better messaging if no Apps are registered

- ui/package.json
- ui/src/app/streams/stream-create/stream-create.component.html
Just turning off the blur action would be bad but the update
to flo ensures we pickup a flo change where graph-to-text
syncing is turned on once you start interacting with the graph.
In this way if you simply switch to a different browser tab and
back, the DSL text field will still retain focus and you won't
lose some text you have in progress that isn't yet complete.
Fixes #423
> Turn off blur action for dsl text field and update flo

- ui/src/app/jobs/components/definition-status.component.ts
Change class from Danger to Info
Updated message from `Deleted` to `No Task Definition`.
resolves #579
> Change the no task definition message on jobs

- ui/src/app/streams/flo/support/view-helper.ts
All options are the same as default except shortLinkLength which has been reduced to 0. Normally if link length is < shortLinkLength then the size of the tools is halved.
resolves #393
> Override link options to prevent link tools resizing

- ui/src/app/streams/stream-create-dialog/stream-create-dialog.component.html
- ui/src/app/streams/stream-definitions/stream-definitions.component.html
Resolve #594
- (re)enable the deploy checkbox in stream-create dialog
- remove the skipper not-supported tooltip button
> Re-enable Stream deploy options for Skipper mode

- ui/src/app/streams/flo/graph-to-text.spec.ts
- ui/src/app/streams/flo/graph-to-text.ts
Without this change if the first stream in a graph is a tap stream
the graph to text algorithm will make a mistake and not treat it
as a tap stream because Array.find returns 0 in this case (because
it is stream 0 that is a tap stream). 0 is treated as false. It
is better to check the Array.find call returned a result (i.e.
result is not undefined)
Fixes #603
> Ensure recognize tap streams when computing text from graph

- ui/package.json
- ui/src/polyfills.ts
- ui/src/styles.scss
* Remove .fade css animation from styles (main cause of issue)
* Add web-animations-js polyfill so that web animations work in Safari
- needed by the busy module so that fade-ins/outs still work
* Fixes the issues in Safari and Firefox
fixes https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/574
> gh-574 Fix Safari/FF browser overlay issue

- ui/src/app/shared/services/shared-apps.service.ts
- ui/src/app/tasks/flo/render.service.ts
- ui/src/app/tasks/tasks.service.ts
- ui/src/app/tests/mocks/shared-app.ts
Fixes #638 
Adjust API to use `ApplicationType` enum type rather than `any` type to match signature of `#getAppInfo(...)`
Add fix for #615 to Tasks rendering
> Use ApplicationType in SharedAppService#getApps() rather than `any` type

- ui/src/app/streams/stream-deploy/builder/builder.component.ts
- ui/src/app/streams/stream-deploy/stream-deploy.component.ts
- Ignore sensitive property value on deploy stream
- Fix parsing line: app.foo=#jsonPath(payload,'$.lang')=='en' is now correctly parse
- Title dialog app property: remove version if skipper is not enable
Resolves spring-cloud/spring-cloud-dataflow-ui#780
> Stream deploy: Fix property issues

- ui/package.json
- ui/src/app/shared/services/group-route.service.ts
- ui/src/app/tests/mocks/group-route.ts
* Add `node-uuid` dependency
* Update code
* Ensure that lint errors pertaining to `Forbidden bitwise operation` no longer occur
resolves https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/852
> gh-852 Use a dedicated UUID/GUID library

- ui/src/app/tasks/task-launch/task-launch.component.html
- ui/src/app/tasks/task-launch/task-launch.component.ts
- ui/src/app/tasks/task-launch/task-launch.validator.spec.ts
- ui/src/app/tasks/task-launch/task-launch.validator.ts
- ui/src/app/tasks/task-schedule-create/task-schedule-create.component.html
- ui/src/app/tasks/task-schedule-create/task-schedule-create.component.ts
Resolves #937
Deployment properties: the key should start with ‘app.’ or ‘deployer.’ or ‘scheduler.’
> Task / Scheduler: enforce rules for deployment properties

- ui/src/app/apps/apps-add/apps-add.validator.ts
- ui/src/app/layout/navigation/search/search.component.ts
- ui/src/app/streams/streams.service.spec.ts
- ui/src/app/streams/streams.service.ts
- ui/src/app/streams/streams/streams.component.html
- ui/src/app/streams/streams/streams.component.spec.ts
- ui/src/app/tasks/task-definitions/task-definitions.component.html
- ui/src/app/tasks/task-definitions/task-definitions.component.spec.ts
- ui/src/app/tasks/tasks.service.ts
- ui/src/app/tests/mocks/mock-data.ts
- ui/src/app/tests/mocks/streams.ts
- ui/src/app/tests/mocks/tasks.ts
- Given the JPA configuration changes in the SCDF core 2.x, we need to use the corresponding names for the sorting.
- Update both the stream/task defintiions pageable query sort params
Resolves #1000
> Fix sort names for stream/task definitions

- ui/package.json
Fixes #996 
Also upgrade Flo to angular 7.1.1 and JointJS 2.2.1
> Upgrade Flo to 0.8.6 and get the fix for overlapping links

- ui/src/app/about/about.service.spec.ts
- ui/src/app/about/components/about-more/about-details.component.html
- ui/src/app/about/components/about-more/about-details.component.spec.ts
- ui/src/app/apps/apps/apps.component.html
- ui/src/app/auth/auth.service.spec.ts
- ui/src/app/auth/feature-disabled.component.spec.ts
- ui/src/app/auth/logout.component.spec.ts
- ui/src/app/auth/logout.component.ts
- ui/src/app/auth/support/auth.guard.ts
- ui/src/app/shared/model/about/about-info.model.spec.ts
- ui/src/app/shared/model/about/security-info.model.spec.ts
- ui/src/app/shared/model/about/security-info.model.ts
- ui/src/app/tests/mocks/about.ts
- ui/src/app/tests/mocks/auth.ts
- remove occurrences of `securityInfo` properties `isAuthorizationEnabled` and `isFormLogin`
- fix tests
- fix + refactor `feature-disabled` component spec
- fix small spelling issue on `About` details page
- remove `AuthorizationEnabled` and `FormLogin` references from `About` details page
resolves https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1004
> gh-1004 Fix: Can't access `Add applications` dialog without CREATE role

- pom.xml
- ui/karma-test.sh
This commit updates URLs to prefer the https protocol. Redirects are not followed to avoid accidentally expanding intentionally shortened URLs (i.e. if using a URL shortener).
These URLs were switched to an https URL with a 2xx status. While the status was successful, your review is still recommended.
* http://cloud.spring.io/spring-cloud-dataflow/ with 1 occurrences migrated to:  
https://cloud.spring.io/spring-cloud-dataflow/ ([https](https://cloud.spring.io/spring-cloud-dataflow/) result 200).
* http://karma-runner.github.io with 1 occurrences migrated to:  
https://karma-runner.github.io ([https](https://karma-runner.github.io) result 200).
* http://maven.apache.org/xsd/maven-4.0.0.xsd with 1 occurrences migrated to:  
https://maven.apache.org/xsd/maven-4.0.0.xsd …
> URL Cleanup

- ui/src/app/shared/model/platform.ts
- ui/src/app/streams/stream-deploy/builder/builder.component.html
- ui/src/app/streams/stream-deploy/builder/builder.component.spec.ts
- ui/src/app/streams/stream-deploy/builder/builder.component.ts
- ui/src/app/streams/stream-deploy/stream-deploy.service.ts
- ui/src/app/tests/mocks/mock-data.ts
- ui/src/app/tests/mocks/streams.ts
- Use modal dialog to handle deployment properties per global
and apps using dialog components made for apps.
- Add options field to platform as that is now coming from
skipper via dataflow.
- Change some mocks and add basic tests for StreamDeployBuilderComponent.
- Fixes #1153
> Populate deployer properties

- ui/src/app/shared/flo/properties/properties-dialog.component.html
- Fix case where properties count is exactly limit 50 by
using equal or lower operator.
- Fixes #1172
> Fix PropertiesDialogComponent count limiting

- ui/src/app/shared/flo/properties-groups/properties-groups-dialog.component.html
- ui/src/app/shared/flo/properties-groups/properties-groups-dialog.component.scss
- ui/src/app/shared/flo/properties-groups/properties-groups-dialog.component.ts
- ui/src/app/shared/shared.module.ts
- ui/src/app/streams/stream-deploy/builder/builder.component.ts
- ui/src/app/streams/streams.module.ts
- Add new PropertiesGroupsDialogComponent which is more
opinionated towards showing bigger list of properties.
- Deployment properties are grouped together by group id,
and groups are sorted to get main group first.
- Dialog will collapse first group and after that one group
is usually kept open unless user closes already open group.
- Fixes #1174
Result is something like this:
> Implement deployment properties grouping

- ui/src/app/apps/apps-add/properties/apps-bulk-import-properties.component.ts
- ui/src/app/apps/apps-add/register/apps-register.component.ts
- ui/src/app/apps/apps-add/uri/apps-bulk-import-uri.component.ts
- ui/src/app/apps/apps-unregister/apps-unregister.component.ts
- ui/src/app/streams/stream-create/create-dialog/create-dialog.component.ts
- ui/src/app/streams/stream-deploy/stream-deploy.component.ts
- ui/src/app/streams/streams-deploy/streams-deploy.component.ts
- ui/src/app/streams/streams-destroy/streams-destroy.component.ts
- ui/src/app/streams/streams-undeploy/streams-undeploy.component.ts
- ui/src/app/streams/streams/streams.component.ts
- ui/src/app/tasks/task-definition-create/create-dialog/create-dialog.component.ts
- ui/src/app/tasks/task-definitions-destroy/task-definitions-destroy.component.ts
- ui/src/app/tasks/task-schedule-create/task-schedule-create.component.ts
- ui/src/app/tasks/task-schedules-destroy/task-schedules-destroy.component.ts
- We've used combination of error or complete to unlock
BlockerService where unlock really needs to happen on
both stages as error and complete are terminating. Move
unblock calls to pipeline with finalize.
- This same logic is done to all use of BlockerService.
- Fixes #1176
> Fix blockerService usage for errors

- ui/src/app/shared/flo/support/properties-group-model.ts
- In PropertiesGroupModel instead of just trying to use type
from a metadata, inspect presense of value hints and create
selector if set of values are given.
- Fixes #1187
NOTE: to see any effect needs to be used with https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/pull/292
> Add support using value hints

- ui/src/app/streams/stream-deploy/builder/builder.component.spec.ts
- ui/src/app/streams/stream-deploy/builder/builder.component.ts
- Fix case where property value is actually boolean and
its default value true and then setting it to false.
Now simply doing using `property.value !== null` instead of
`property.value` which would naturally might be false with a boolean type.
- Added test for these two functions getDeploymentProperties and getAppProperties.
- Fixes #1191
> Fix property filtering check in stream deploy

- ui/src/scss/styles.scss
resolves https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1246
> gh-1246 Fix: Grafana icons are missing in Stream, Runtime and Task pages

- ui/src/app/tasks/task-schedules/task-schedules.component.spec.ts
- ui/src/app/tasks/task-schedules/task-schedules.component.ts
- ui/src/app/tasks/tasks-routing.module.ts
- At Schedules list page, user can now click the action drop down for each schedule to create another new schedule.
- Add test
Resolves #1243
> Add drop down action for add new schedule

- ui/src/app/tasks/task-launch/task-launch.component.html
- ui/src/app/tasks/task-schedule-create/task-schedule-create.component.html
- Change `Parameters` from task launch page to `Properties` since they are actually task launch properties.
Also, this avoids confusion from Job parameters vs Task properties
- Fix the same for Schedule creation page
Resolves #1417
> Task launch properties name fix

- ui/src/app/flo/shared/flo.scss
- ui/src/app/flo/stream-flo.module.ts
- ui/src/app/flo/stream/component/runtime-view.component.spec.ts
- ui/src/app/flo/stream/component/runtime-view.component.ts
- ui/src/app/streams/streams/streams.component.html
- ui/src/app/streams/streams/streams.component.spec.ts
- ui/src/app/streams/streams/streams.component.ts
Missing stream graph view able to show instance dots.
If metrics are not to be shown over the stream graph (as message rates are gone), in other words if instance dots are not desired and there are no plans to show any other metrics data of stream runtime data then this SHOULD NOT be merged and instead other related component SHOULD be removed.
cc: @sabbyanandan
> Stream view with instance dots integrated

- ui/src/app/tasks/model/task-definition.spec.ts
- ui/src/app/tasks/model/task-definition.ts
- ui/src/app/tasks/task-definition/task-definition.component.html
- ui/src/app/tasks/task-definitions/task-definitions.component.html
- ui/src/app/tasks/task-definitions/task-definitions.component.spec.ts
- ui/src/app/tasks/task-definitions/task-definitions.component.ts
- ui/src/app/tasks/task-launch/task-launch.component.spec.ts
- ui/src/app/tests/mocks/mock-data.ts
- Check for the task definition attribute `composdTaskElement` and perform disable actions based on this
- Update the corresponding html template files
- Update tests
Resolves #1437
> Disable destroy/schedule actions for sub tasks of a composed task

- ui/src/app/tasks-jobs/schedules/create/create.component.ts
There was not a string but a Task object therefore on the backend you got NoSuchTaskDefinitionException because in the parameter you had got not a taskDefinitionName but and [object Object]
> fix for NoSuchTaskDefinitionException on backend

- ui/src/app/tasks-jobs/executions/execution/execution.component.html
- Move modals out from an inner div so that @ViewChild
can find those and make popups work.
- Fixes #1459
> Move modals into correct position

- ui/package.json
- ui/src/app/shared/flo/support/node-component.ts
- ui/src/app/shared/flo/support/utils.ts
- ui/src/app/shared/services/shared-apps.service.ts
- ui/src/app/streams/components/flo/editor.service.spec.ts
- ui/src/app/streams/components/flo/editor.service.ts
- ui/src/app/streams/components/flo/graph-to-text.spec.ts
- ui/src/app/streams/components/flo/graph-to-text.ts
- ui/src/app/streams/components/flo/properties-editor.service.ts
- ui/src/app/streams/components/flo/properties/stream-properties-source.ts
- ui/src/app/streams/components/flo/render.service.ts
- ui/src/app/streams/components/flo/support/utils.ts
- ui/src/app/streams/components/stream-graph-definition/stream-graph-definition.component.spec.ts
- ui/src/app/streams/components/stream-graph-definition/stream-graph-definition.component.ts
- ui/src/app/tasks/components/flo/editor.service.spec.ts
- ui/src/app/tasks/components/flo/editor.service.ts
- ui/src/app/tasks/components/flo/metamodel.service.ts
- ui/src/app/tasks/components/flo/node/task-node.component.ts
- ui/src/app/tasks/components/flo/properties/task-properties-source.ts
- ui/src/app/tasks/components/flo/render.service.ts
- ui/src/app/tasks/components/flo/support/layout.ts
Moving stream app shapes metadata from `Element.attr(...)` into `Element.prop(...)` (or `Element.set(...)`)
`Element` object is being cloned by JointJS core during various operations properties set with `Element.attr(...)` are being cloned while properties set with 'Element.prop(...)` or Element.set(...) not deep cloned but rather assigned. This allows to have methods and keep cached promises.
JoinJS folks recommended to use `Element.attr(...)` only for SVG dom element attributes and keep the "business" data under `Element.prop(...)'
> Move apps metadata from Element#attr(...) to Element#prop(...)

- ui/package.json
- ui/src/app/streams/components/flo/render.service.ts
1. Switch app name to some string click ok
2. Open **Options** again and remove the name typed in step 1. Click Ok
3. The label should not be bold at this moment anymore (default name shouldn't be bold)
Also there is a fix for creating tap links from by dragging from target port to source port
> Fixes for tap links and default app name

- ui/src/app/app.component.html
- ui/src/app/app.component.ts
- ui/src/app/app.module.ts
- ui/src/app/settings/component/settings.component.html
- ui/src/app/settings/component/settings.component.spec.ts
- ui/src/app/settings/component/settings.component.ts
- ui/src/app/settings/service/settings.service.spec.ts
- ui/src/app/settings/service/settings.service.ts
- ui/src/app/settings/settings-routing.module.ts
- ui/src/app/settings/settings.module.ts
- ui/src/app/settings/store/settings.action.ts
- ui/src/app/settings/store/settings.effect.spec.ts
- ui/src/app/settings/store/settings.effect.ts
- ui/src/app/settings/store/settings.reducer.spec.ts
- ui/src/app/settings/store/settings.reducer.ts
- ui/src/app/shared/model/setting.ts
- Remove theme button in favour of changing it from
a new settings page.
- Model for setting is a simple key/value pair but via
an interface if we need some more data in it.
- Add store concept and facilities around it.
- For now this settings store is dummy as it doesn't
yet integration into any permanent store.
- Change Manage item as settings page took the cog shape.
- Fixes #1477
> Add settings page

- ui/src/app/flo/shared/properties/properties-dialog.component.html
- ui/src/app/flo/shared/properties/properties-dialog.component.ts
- ui/src/app/flo/stream/node/stream-node.component.html
- ui/src/app/flo/stream/node/stream-node.component.ts
- ui/src/app/flo/stream/properties-editor.service.ts
- ui/src/app/flo/stream/properties/stream-properties-dialog.component.ts
- ui/src/app/flo/task/editor.service.spec.ts
- ui/src/app/flo/task/node/task-node.component.html
- ui/src/app/flo/task/node/task-node.component.ts
- ui/src/app/flo/task/properties/task-properties-dialog-component.ts
- ui/src/app/flo/task/render.service.spec.ts
- ui/src/app/flo/task/render.service.ts
- ui/src/app/shared/service/modal.service.ts
Fixes #1495 
Generally makes Clarity modal dialog easier to use (similarly to **ngx-bootstrap** lib **BsModalService**) across application.
> Modal Service with Clarity

- ui/package.json
Fix the following:
- create a stream
- show the graph in the list streams
- Go to create stream
- file | log => no graph
(Fixed in Flo - problem is two Flo editors hence lookup for HTML elements by id should be parent scoped)
> Fix 5% zoom in create stream page after switching stream list

- ui/src/app/tasks-jobs/jobs/jobs.component.ts
Addresses #1620.
Came across this. When a job isn't properly tagged as a Task app, it causes a 404 which causes the job executions screen to spin without any prompts to the user. This can be a bit misleading, so this change adds a notification on the screen when this happens.
> Add messaging when error from thinexecutions endpoint on Job executions screen

- ui/src/app/flo/stream/node/stream-node.component.html
- ui/src/app/flo/task/node/task-node.component.html
Fixes #1624 
Let width of the tooltip be equal to the table width as table width is well limited already
> Canvas node tooltip width

- ui/src/app/shared/model/task.model.ts
- ui/src/app/tasks-jobs/tasks/launch/builder/builder.component.html
- ui/src/app/tasks-jobs/tasks/launch/builder/builder.component.ts
- ui/src/app/tasks-jobs/tasks/launch/task-launch.service.ts
- ui/src/app/tests/service/task-launch.service.mock.ts
- As loading ctr options may be a tad slow as it backing
metadata may come from a jar needed to get downloaded and
may result error, etc. Delay this operation after
initial form is built and then update needed form states.
- Also skip load if task is not ctr.
- Fixes #1644
NOTE: for existing functionality to see behaviour, just restart a server and zap ~/.m2/repository/org/springframework/cloud/spring-cloud-dataflow-composed-task-runner.
> Delay loading ctr options

- ui/src/app/shared/api/task.service.ts
- ui/src/app/tasks-jobs/tasks/launch/launch.component.spec.ts
- ui/src/app/tasks-jobs/tasks/launch/launch.component.ts
- ui/src/app/tests/api/task.service.mock.ts
- Now simple parse body response from a task launch
and redirect to returned task execution.
- No special handling of batch
(aka trying to redirect job execution instead) as batch
is expected to be a task?
- Fixes #1599
> Redirect to task execution after launch

- ui/src/app/shared/model/task-execution.model.ts
- ui/src/app/shared/model/task.model.ts
- ui/src/app/tasks-jobs/tasks/launch/builder/builder.component.spec.ts
- ui/src/app/tasks-jobs/tasks/launch/builder/builder.component.ts
- ui/src/app/tasks-jobs/tasks/launch/free-text/free-text.component.html
- ui/src/app/tasks-jobs/tasks/launch/task-launch.service.ts
- ui/src/app/tests/service/task-launch.service.mock.ts
- Get deploy props from last execution and re-calculate
properties so that those will get shows in a form in
a same way when you'd switch between build/free-text.
- We skip expected sensity values as those are not
known anymore.
- Fixes #1651
> Dehydrate task launch deployment properties

- ui/src/app/tasks-jobs/tasks/launch/task-launch.service.ts
- Within rxjs chain it was supposed to do call for
appService.getAppVersions with every distict app name
but ended up terminatig chain too early, thus
getting only one.
- Now do further pipe so that we can listen and reduce
into one single map.
- Fixes #1662
> Get all results from task app versions queries

- ui/src/scss/styles.scss
The logs available in SCDF can contain quite long lines. Currently, the horizontal scroll bar for that is only visible when one scrolls to the very bottom of the log. This makes it unnecessarily complicated to read the long lines, in my opinion.
Clarity's `modal-body` sets `max-height` to `70vh`. Only if this is inherited for the log, the horizontal scroll bar is always shown.
I observed the problem in both Firefox and Chrome. The PR fixes it for both. The only other use of `clr-log` is for the exit description of steps. With the PR applied, that widget looks same as before in both browsers, respectively.
Below two screenshots from Firefox with the PR applied:
> Show horizontal scroll for logs not only at bottom

- ui/src/app/tasks-jobs/tasks/launch/free-text/free-text.component.scss
In Firefox, line breaks are not shown in the `textarea` widgets when launching tasks. It currently looks as in the screenshot below. In Chrome, everything looks fine.
The PR changes `white-space` from `nowrap` to `pre`. That way, in both browsers
- line breaks are shown,
- and long lines are not wrapped
I also set `overflow-x` from `scroll` to `auto` to only show the horizontal scroll bar when there is actually something to scroll.
That the arguments are flagged as invalid in the screenshot is a separate issue: https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1686
> Fix line breaks in textarea for Firefox

- ui/src/app/shared/model/task-execution.model.ts
When a user wants the sub tasks of a composed task to be started with the argument `foo=bar`, they can start the composed task with the argument `--composed-task-arguments=foo=bar`. On the page for the execution of the composed task, the `=bar` is currently scrapped as seen here:
With the proposed change, it looks like this
> Split task arguments only at first equal sign

- ui/src/app/tasks-jobs/jobs/execution/execution.component.html
- ui/src/app/tasks-jobs/jobs/jobs.component.html
Fix the issue #1747 : 
Currently, The "Restart The Job" button is not enabled for the job execution if its status is "Stopped". The restart button is disabled in issue #1407 and the pull request #1408. It is only enabled for the "Failed" job. I think it should be enabled for the "Stopped" job as well.
Please help to review.
> Enable restart button when job status is STOPPED

- ui/src/app/about/info/info.component.scss
- ui/src/app/about/info/info.component.ts
- Solved rendering of icons inside 'About' modal
> fix: Logos missing in about dialog

- ui/src/app/layout/nav/nav.component.html
I'm not a native speaker but I think only one `s` is added to form the plural of compound nouns.
> Fix plural of compound nouns

- ui/src/app/tasks-jobs/tasks/create/create.component.html
Fixed label in 'Create task'.  
It happens when editing task name input with unwanted characters.
Resolves #1805.
Before:
After:
> Solve validation message on invalid task name input

- ui/src/app/app.module.ts
Spring Security Filter resulted in 403 when URL contained //
```
org.springframework.security.web.firewall.RequestRejectedException: The request was rejected because the URL contained a potentially malicious String "//"
at org.springframework.security.web.firewall.StrictHttpFirewall.rejectedBlocklistedUrls(StrictHttpFirewall.java:456)
at org.springframework.security.web.firewall.StrictHttpFirewall.getFirewalledRequest(StrictHttpFirewall.java:429)
at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:196)
```
All other uses of `calculateAssetUrl()` assumed it ends with a `/`
> Fix URL for en.json to prevent 403

- ui/src/app/tasks-jobs/tasks/tasks.component.html
Resolves #1848 
Found one missing translation on task page ("Description")
"Definition" and "Status" are already translated into the code. 
When looking on German translations it seemed to me they were wrong but in the end "Definition" and "Status" are valid german words for english "Definition" and "Status".
> Translations on tasks table

- ui/src/app/layout/theme/dark-theme.ts
- ui/src/app/layout/theme/default-theme.ts
- ui/src/scss/styles.scss
fixes: https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1920
The highlight of the datagrid-rows is much less intrusive, now.
> fix: datagrid highlight color

- ui/src/app/tasks-jobs/jobs/step/step.component.html
When we select specific step execution from the job execution screen, on the left where the task execution details are shown, while showing the duration, the label Start Time is used instead of duration.
> Fix duration label key

- ui/src/app/manage/tools/tools.component.html
Fixes: https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1942
`CLEAN UP TASK EXECUTIONS` has been moved into the container with `appFeature="tasks"`
Because this looks weird, as on the right side there would be two `app-view-card` and on the left only one I decided to make them all `clr-col-lg-12` to get the max width of the parent container.
> fix: clean up should be available if streams are disabled

- .github/workflows/build-snapshot-worker.yml
- .github/workflows/ci-pr.yml
- .github/workflows/ci.yml
- .github/workflows/milestone-worker.yml
- .github/workflows/next-dev-version-worker.yml
- .github/workflows/release-worker.yml
Update setup-jfrog-cli to use `JF_ENV_SPRING` instead of `JF_ARTIFACTORY_SPRING` 
Added `JF_URL`
Added reference to `${{ vars.JF_SERVER_ID }}` in place of `repo.spring.io`
Remove maven setup and add --use-wrapper
> [CI] Update jfrog cli to v3 
